services:
  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bash -c "bundle install && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/uo_app
      - bundle_data:/usr/local/bundle
    ports:
      - "3001:3001"
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  postgres_data:
  bundle_data: